# just is a command runner, Justfile is very similar to Makefile, but simpler.
############################################################################
#
#  Common recipes
#
############################################################################

# List all recipes
_default:
    @printf '\033[1;36mnixcfg recipes\033[0m\n\n'
    @printf '\033[1;33mUsage:\033[0m just <recipe> [args...]\n\n'
    @just --list --list-heading $'Available recipes:\n\n'

# Generate {ci,edconfig} files
[group('flake')]
gen target:
    nix run .#{{ if target == "ci" { "render-workflows" } else if target == "edconfig" { "gen-files" } else { error("unknown target: " + target) } }}

# Update flake inputs
[group('flake')]
update *inputs:
    nix flake update {{ inputs }} --commit-lock-file

# Update all nixpkgs inputs
[group('flake')]
update-nixpkgs: (update "nixpkgs" "nixpkgs-unstable-small")

############################################################################
#
#  Secrets (sops + age)
#
############################################################################

# Derive this machine's age private key from its ssh ed25519 key, install
# at ~/.config/sops/age/keys.txt. Run once per machine. The corresponding
# public key (age1...) must already be a recipient in .sops.yaml.
[group('secrets')]
sops-bootstrap:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ -f ~/.config/sops/age/keys.txt ]]; then
        echo "~/.config/sops/age/keys.txt already exists; skipping."
        exit 0
    fi
    mkdir -p ~/.config/sops/age
    ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt
    chmod 600 ~/.config/sops/age/keys.txt
    echo "wrote ~/.config/sops/age/keys.txt"
    echo "this machine's age recipient (must be in .sops.yaml):"
    ssh-to-age -i ~/.ssh/id_ed25519.pub

# Regenerate .sops.yaml from keys/*.pub, then re-encrypt every
# YAML secrets under secrets/ and k8s/secrets/. Run after keys change.
[group('secrets')]
sops-rekey:
    #!/usr/bin/env bash
    set -euo pipefail
    shopt -s nullglob
    user_pubs=(keys/aly_*.pub)
    host_pubs=(keys/root_*.pub)
    {
        cat <<'EOF'
    # Auto-generated by `just sops-rekey` from keys/*.pub.
    # Every recipient can decrypt every secret. To add or remove a
    # machine, add or remove its .pub file and re-run `just sops-rekey`.
    keys:
      # === user keys (aly@<host>) ===
    EOF
        for f in "${user_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#aly_}
            age=$(ssh-to-age -i "$f")
            printf '  - &user_aly_%s %s\n' "$host" "$age"
        done
        echo "  # === host keys (root@<host>) ==="
        for f in "${host_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#root_}
            age=$(ssh-to-age -i "$f")
            printf '  - &host_%s %s\n' "$host" "$age"
        done
        cat <<'EOF'

    creation_rules:
      - path_regex: ^(secrets|k8s/secrets)/.*\.ya?ml$
        key_groups:
          - age:
    EOF
        for f in "${user_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#aly_}
            printf '          - *user_aly_%s\n' "$host"
        done
        for f in "${host_pubs[@]}"; do
            host=$(basename "$f" .pub); host=${host#root_}
            printf '          - *host_%s\n' "$host"
        done
    } > .sops.yaml
    echo "regenerated .sops.yaml"
    shopt -s globstar
    for f in secrets/**/*.yaml secrets/**/*.yml k8s/secrets/**/*.yaml k8s/secrets/**/*.yml; do
        if [[ "$(sops filestatus "$f")" == *'"encrypted":true'* ]]; then
            echo "rekeying $f"
            sops updatekeys -y "$f"
        fi
    done

# Edit a sops-encrypted secrets file. Usage: just sops-edit tailscale.yaml
[group('secrets')]
[positional-arguments]
sops-edit FILE:
    #!/usr/bin/env bash
    set -euo pipefail
    case "$1" in
        secrets/*|k8s/secrets/*) sops "$1" ;;
        *) sops "secrets/$1" ;;
    esac

############################################################################
#
#  NixOS
#
############################################################################
############################################################################
#
#  Darwin
#
############################################################################

# Reset launchpad to force it to reindex Applications
[group('desktop')]
[macos]
reset-launchpad:
    defaults write com.apple.dock ResetLaunchPad -bool true
    killall Dock
