apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aly-codes.yaml
  - atbbs.yaml
  - morgan.yaml
  - morsels.yaml
  - skytrace.yaml
  - slingshot.yaml
  - snrld.yaml
  - switchyard.yaml
  - tranquil-pds.yaml
  - vaultwarden.yaml
