apiVersion: apps/v1
kind: Deployment
metadata:
  name: aly-codes
  namespace: aly-codes
  labels:
    app: aly-codes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aly-codes
  template:
    metadata:
      labels:
        app: aly-codes
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: aly-codes
      containers:
        - name: aly-codes
          image: ghcr.io/alyraffauf/aly.codes:latest@sha256:baf0f18f1f9215d5dd99d0648574d9883432f653106503888a16874554fa91b9
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: aly-codes
  namespace: aly-codes
spec:
  selector:
    app: aly-codes
  ports:
    - name: http
      port: 80
      targetPort: http
