apiVersion: apps/v1
kind: Deployment
metadata:
  name: skytrace
  namespace: skytrace
  labels:
    app: skytrace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skytrace
  template:
    metadata:
      labels:
        app: skytrace
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: skytrace
      containers:
        - name: skytrace
          image: ghcr.io/alyraffauf/skytrace:latest@sha256:c72908c2fbfa473a2e2c51c22862d8f3efb623fe5b3d643e599629631539a249
          env:
            - name: SKYTRACE_BLOCK_TARGET_DID
              value: "did:plc:jwxdvd2mdtdq7la7toiy2rjc"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: skytrace
  namespace: skytrace
spec:
  selector:
    app: skytrace
  ports:
    - name: http
      port: 80
      targetPort: http
