apiVersion: apps/v1
kind: Deployment
metadata:
  name: snrld
  namespace: snrld
  labels:
    app: snrld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snrld
  template:
    metadata:
      labels:
        app: snrld
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: snrld
      containers:
        - name: snrld
          image: ghcr.io/alyraffauf/snrld:latest@sha256:73d8dcc3234367b71b3e23356b0dd1a812ffed1672a4431e3b7f14dcd12845d2
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: snrld
  namespace: snrld
spec:
  selector:
    app: snrld
  ports:
    - name: http
      port: 80
      targetPort: http
