apiVersion: apps/v1
kind: Deployment
metadata:
  name: snrld
  namespace: snrld
  labels:
    app: snrld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snrld
  template:
    metadata:
      labels:
        app: snrld
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: snrld
      containers:
        - name: snrld
          image: ghcr.io/alyraffauf/snrld:latest@sha256:a69bdef8022a12c7fd52bc8cef1cca791a4b6f47d383c5d9687309425e3a9bfe
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: snrld
  namespace: snrld
spec:
  selector:
    app: snrld
  ports:
    - name: http
      port: 80
      targetPort: http
