apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-shared
  namespace: cnpg-system
spec:
  instances: 2
  postgresql:
    parameters:
      max_connections: "200"
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6@sha256:6d207b34e2859e55ee7653d57321ef28c86d9c4b42e9e66609756565f0cc5542
  storage:
    storageClass: local-path
    size: 5Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-shared-backups
  managed:
    roles:
      - name: vaultwarden
        login: true
        passwordSecret:
          name: vaultwarden-pg-creds
      - name: tranquil
        login: true
        passwordSecret:
          name: tranquil-pg-creds
