apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pg-shared-metrics
  namespace: cnpg-system
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: pg-shared
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: alloy-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: alloy
              app.kubernetes.io/instance: alloy
      ports:
        - protocol: TCP
          port: 9187
