apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sinnoh-public-ingress
  namespace: kube-system
spec:
  secretName: sinnoh-public-ingress-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - aly.codes
    - www.aly.codes
    - status.aly.codes
    - switchyard.aly.codes
    - vibes.aly.codes
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - --accesslog.fields.queryparameters.defaultmode=drop
    metrics:
      prometheus:
        addRoutersLabels: true
        addServicesLabels: true
        buckets: "0.001,0.0025,0.005,0.01,0.025,0.05,0.1,0.25,0.5,1,2.5,5,10,30"
    logs:
      access:
        enabled: true
        format: json
    resources:
      requests:
        cpu: 25m
        memory: 192Mi
      limits:
        memory: 256Mi
    ports:
      telnet:
        port: 2323
        exposedPort: 23
        protocol: TCP
        expose:
          default: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: sinnoh-public-ingress-tls
