apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - cert-manager.yaml
  - cnpg.yaml
  - barman-cloud.yaml
  - secrets.yaml
  - postgres-backups.yaml
  - postgres.yaml
  - tailscale-dns.yaml
  - alloy.yaml
  - vaultwarden.yaml
  - tranquil-pds.yaml
  - pacifico.yaml
  - letsencrypt.yaml
  - traefik.yaml
  - atbbs.yaml
  - aly-codes.yaml
  - haunt.yaml
  - skytrace.yaml
  - snrld.yaml
  - morgan.yaml
  - switchyard.yaml
  - morsels.yaml
  - slingshot.yaml
  - ingress.yaml
