---
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  NIX_CONFIG: "access-tokens = github.com=${{ github.token }}"
jobs:
  build:
    name: Build ${{ matrix.host }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          - sunnyshore
          - canalave
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@ceedf095f4ec1a097402bc6bd80831f2e1a6fde6 # v2.0.0
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - name: Cachix
        uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: alyraffauf
      - name: Build NixOS host
        run: >-
          nix build --accept-flake-config --print-out-paths
          .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
name: build-nixos
"on":
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - _img/**
  workflow_dispatch: {}
